import type { RolibotReport } from "./types";

export const mockReport: RolibotReport = {
  ok: true,
  brand: "RoliBot NBA",
  generated_at: new Date().toISOString().slice(0, 10),
  bankroll: 1000,
  kelly_fraction: 0.25,
  max_bet_pct: 0.05,
  how_to_use: [
    "Set BANKROLL in nba_predictor.py to your actual bankroll.",
    "Copy STRONG BET + Kelly amounts to your sportsbook.",
    "SAFE PROP PARLAY #1 = steady-value template.",
    "Cap RISKY PARLAYS at $10–20 max.",
    "HOT STREAK parlays = players trending up vs season average.",
    "Players listed Out (ESPN injury feed) are removed from props and parlays.",
    "Second run the same day is faster when model cache hits.",
    "Delete model_cache.pkl weekly if you want a full retrain.",
    "Never bet more than you can afford to lose.",
  ],
  pipeline: {
    season_pull: [
      { season: "2018-19", rows: 2460 },
      { season: "2019-20", rows: 2118 },
      { season: "2024-25", rows: 2460 },
    ],
    current_nba_season: "2025-26",
    raw_season_rows: 16578,
    clean_merged_games: 8023,
    home_win_rate_merged: 0.557,
    date_from: "2018-11-04",
    date_to: "2026-04-02",
    train_games: 6418,
    test_games: 1605,
    schedule_tonight: 6,
    props_fetch: [
      { team: "CHA", opponent: "PHX", viable_props: 29 },
      { team: "PHX", opponent: "CHA", viable_props: 19 },
    ],
    props_teams_fetched: 12,
    props_skipped_injury: 0,
    injury_report: {
      source: "espn",
      fetched_ok: true,
      n_out: 2,
      out_players: [
        { player: "Demo Player (Out)", team: "Demo Team", status: "Out" },
        { player: "Another Out Player", team: "Demo Team", status: "Out" },
      ],
    },
  },
  training: {
    xgb_eval_log: [
      { iteration: 0, validation_logloss: 0.68878 },
      { iteration: 100, validation_logloss: 0.62038 },
      { iteration: 200, validation_logloss: 0.61874 },
    ],
    from_cache: false,
    feature_importance_saved: true,
    feature_importance_path: "nba_bot/feature_importance.png",
  },
  run_meta: {
    cache_line: "MISS — retrained & saved",
    games_predicted_tonight: 6,
    breakeven_note: "~52.4% implied win rate vs standard -110 sides",
  },
  model: {
    name: "Ensemble (XGBoost 60% + Random Forest 40%)",
    accuracy: 0.664,
    logloss: 0.6035,
    edge_vs_book_pp: 14.0,
    n_features: 64,
    n_train_games: 6418,
    cache_hit: false,
  },
  evaluation: {
    classification_report: {
      "Away Win": { precision: 0.69, recall: 0.5, "f1-score": 0.58, support: 743 },
      "Home Win": { precision: 0.65, recall: 0.81, "f1-score": 0.72, support: 862 },
      accuracy: 0.664,
      "macro avg": { precision: 0.67, recall: 0.65, "f1-score": 0.65, support: 1605 },
      "weighted avg": { precision: 0.67, recall: 0.66, "f1-score": 0.65, support: 1605 },
    },
    calibration_bins: [
      { range: "50%–55%", actual_win_rate: 0.534, n_games: 337 },
      { range: "55%–60%", actual_win_rate: 0.558, n_games: 113 },
    ],
    sportsbook_breakeven: 0.524,
  },
  games: [
    {
      home_abbr: "LAC",
      away_abbr: "SAS",
      home_name: "Los Angeles Clippers",
      away_name: "San Antonio Spurs",
      prob_home: 0.798,
      prob_away: 0.202,
      pick_name: "Los Angeles Clippers",
      pick_abbr: "LAC",
      pick_prob: 0.798,
      pick_side: "HOME",
      pick_odds: "-394",
      edge: 0.298,
      confidence: "🔥 STRONG",
      stars: "★★★",
      kelly_amt: 0,
      props: [],
      top_props: [
        {
          player: "Ivica Zubac",
          team: "LAC",
          label: "8+ Rebounds",
          hit_rate: 0.96,
          raw_hr: 0.96,
          avg: 13.1,
          avg_recent: 12,
          n_games: 20,
          trend: "",
          min_flag: "",
          opp_factor: 0.97,
          stars: "★★★",
          confidence_tier: "🔥 STRONG",
        },
        {
          player: "Ivica Zubac",
          team: "LAC",
          label: "10+ Rebounds",
          hit_rate: 0.96,
          raw_hr: 0.96,
          avg: 13.1,
          avg_recent: 12,
          n_games: 20,
          trend: "",
          min_flag: "",
          opp_factor: 0.97,
          stars: "★★★",
          confidence_tier: "🔥 STRONG",
        },
        {
          player: "Victor Wembanyama",
          team: "SAS",
          label: "15+ Points",
          hit_rate: 0.95,
          raw_hr: 0.95,
          avg: 18.2,
          avg_recent: 17,
          n_games: 20,
          trend: "📉 COOLING",
          min_flag: "",
          opp_factor: 1.09,
          stars: "★★★",
          confidence_tier: "🔥 STRONG",
        },
      ],
      risky_props: [
        {
          player: "Victor Wembanyama",
          team: "SAS",
          label: "3+ Three-Pointers",
          hit_rate: 0.48,
          raw_hr: 0.48,
          avg: 2.7,
          avg_recent: 2.1,
          n_games: 20,
          trend: "🥶 COLD",
          min_flag: "",
          opp_factor: 1,
        },
        {
          player: "Ivica Zubac",
          team: "LAC",
          label: "3+ Assists",
          hit_rate: 0.48,
          raw_hr: 0.48,
          avg: 3.2,
          avg_recent: 3.0,
          n_games: 20,
          trend: "🔥 HOT",
          min_flag: "",
          opp_factor: 1,
        },
      ],
      minutes_warnings: [],
    },
  ],
  bet_slip: {
    strong: [
      {
        home_abbr: "LAC",
        away_abbr: "SAS",
        home_name: "Los Angeles Clippers",
        away_name: "San Antonio Spurs",
        prob_home: 0.798,
        prob_away: 0.202,
        pick_name: "Los Angeles Clippers",
        pick_abbr: "LAC",
        pick_prob: 0.798,
        pick_side: "HOME",
        pick_odds: "-394",
        edge: 0.298,
        confidence: "🔥 STRONG",
        stars: "★★★",
        kelly_amt: 0,
        props: [],
      },
    ],
    good: [
      {
        home_abbr: "DET",
        away_abbr: "MIN",
        home_name: "Detroit Pistons",
        away_name: "Minnesota Timberwolves",
        prob_home: 0.408,
        prob_away: 0.592,
        pick_name: "Minnesota Timberwolves",
        pick_abbr: "MIN",
        pick_prob: 0.592,
        pick_side: "AWAY",
        pick_odds: "-145",
        edge: 0.092,
        confidence: "✅ GOOD",
        stars: "★★☆",
        kelly_amt: 0.13,
        props: [],
      },
    ],
    lean: [],
    skip: [
      {
        home_name: "Oklahoma City Thunder",
        away_name: "Los Angeles Lakers",
        home_abbr: "OKC",
        away_abbr: "LAL",
      },
    ],
    total_kelly: 0.13,
    total_kelly_pct_bankroll: 0.00013,
  },
  parlays: {
    safe_props: [
      {
        n: 4,
        combined: 0.764,
        payout: 30.88,
        implied_american: "-324",
        kelly: 8.15,
        legs: [
          { player: "Harrison Barnes", label: "1+ Three-Pointers", hit_rate: 0.95, trend: "🔥 HOT", stars: "★★★", confidence: "🔥 STRONG" },
          { player: "Anthony Edwards", label: "10+ Points", hit_rate: 0.94, trend: "📈 WARM", stars: "★★★", confidence: "🔥 STRONG" },
          { player: "James Harden", label: "15+ Points", hit_rate: 0.93, trend: "📈 WARM", stars: "★★★", confidence: "🔥 STRONG" },
          { player: "LaMelo Ball", label: "3+ Assists", hit_rate: 0.92, trend: "🔥 HOT", stars: "★★★", confidence: "🔥 STRONG" },
        ],
      },
    ],
    risky_props: [
      {
        n: 2,
        combined: 0.23,
        payout: 334.03,
        implied_american: "+334",
        legs: [
          { player: "Ivica Zubac", label: "3+ Assists", hit_rate: 0.48, trend: "🔥 HOT", avg: 3.2 },
          { player: "Jalen Duren", label: "3+ Assists", hit_rate: 0.48, trend: "🔥 HOT", avg: 2.9 },
        ],
      },
    ],
    mixed: [],
    hot: [
      {
        n: 3,
        combined: 0.698,
        payout: 43.26,
        implied_american: "-230",
        legs: [
          { player: "Harrison Barnes", label: "1+ Three-Pointers", hit_rate: 0.95, trend: "🔥 HOT", avg: 2.5, avg_recent: 3.2 },
          { player: "Kevin Durant", label: "1+ Three-Pointers", hit_rate: 0.86, trend: "🔥 HOT", avg: 3.0, avg_recent: 3.6 },
          { player: "Rudy Gobert", label: "10+ Points", hit_rate: 0.85, trend: "🔥 HOT", avg: 15.4, avg_recent: 19.2 },
        ],
      },
    ],
    best_team: {
      legs: [
        { pick_name: "Los Angeles Clippers", pick_abbr: "LAC", pick_prob: 0.798, pick_side: "HOME" },
        { pick_name: "Phoenix Suns", pick_abbr: "PHX", pick_prob: 0.735, pick_side: "AWAY" },
      ],
      combined: 0.586,
      payout: 70.71,
      kelly: 0.44,
    },
    best_safe_prop: {
      n: 4,
      combined: 0.764,
      payout: 30.88,
      implied_american: "-324",
      kelly: 8.15,
      legs: [
        { player: "Harrison Barnes", label: "1+ Three-Pointers", hit_rate: 0.95, trend: "🔥 HOT", stars: "★★★", confidence: "🔥 STRONG" },
        { player: "Anthony Edwards", label: "10+ Points", hit_rate: 0.94, trend: "📈 WARM", stars: "★★★", confidence: "🔥 STRONG" },
        { player: "James Harden", label: "15+ Points", hit_rate: 0.93, trend: "📈 WARM", stars: "★★★", confidence: "🔥 STRONG" },
        { player: "LaMelo Ball", label: "3+ Assists", hit_rate: 0.92, trend: "🔥 HOT", stars: "★★★", confidence: "🔥 STRONG" },
      ],
    },
    best_risky_prop: {
      n: 2,
      combined: 0.23,
      payout: 334.03,
      implied_american: "+334",
      legs: [
        { player: "Ivica Zubac", label: "3+ Assists", hit_rate: 0.48, trend: "🔥 HOT", avg: 3.2 },
        { player: "Jalen Duren", label: "3+ Assists", hit_rate: 0.48, trend: "🔥 HOT", avg: 2.9 },
      ],
    },
  },
  highlights: { best_prop_parlay_kelly: 0.25 },
  props_summary: {
    n_safe: 173,
    n_risky: 110,
    best_prop: {
      player: "Ivica Zubac",
      label: "8+ Rebounds",
      hit_rate: 0.96,
      avg: 13.1,
      n_games: 20,
      trend: "",
    },
  },
  disclaimer: "Demo data. For entertainment only.",
};
